# Generated by Django 4.2.7 on 2023-11-21 10:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('ad_title', models.CharField(max_length=150)),
                ('ad_text_card', models.TextField()),
                ('ad_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ad_img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('news_title', models.CharField(max_length=150)),
                ('news_text_card', models.TextField()),
                ('news_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('news_img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('inner', models.ManyToManyField(null=True, to='app.news')),
            ],
        ),
    ]
